# Generated by Django 6.0 on 2026-03-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Tên')),
                ('lname', models.CharField(max_length=50, verbose_name='Họ')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Điện thoại')),
                ('mobile', models.CharField(max_length=20, verbose_name='Di động')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('status', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Phụ huynh',
                'verbose_name_plural': 'Phụ huynh',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20, unique=True, verbose_name='Mã số sinh viên')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('date_of_join', models.DateField(auto_now_add=True, verbose_name='Ngày vào học')),
                ('status', models.BooleanField(default=True, verbose_name='Đang học')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parent', verbose_name='Phụ huynh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ sinh viên',
                'verbose_name_plural': 'Hồ sơ sinh viên',
            },
        ),
    ]
