# Generated by Django 6.0.6 on 2026-06-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Liên hệ khẩn cấp', 'verbose_name_plural': 'Liên hệ khẩn cấp'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_join',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày nhập học'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parent', verbose_name='Người liên hệ khẩn cấp'),
        ),
    ]
