# Generated by Django 6.0.7 on 2026-07-24 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lecturer_code', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(blank=True, help_text='Cơ hữu, Thỉnh giảng', max_length=50, null=True)),
                ('teaching_domain', models.TextField(blank=True, help_text='Chuyên môn/Lĩnh vực giảng dạy', null=True)),
                ('join_date', models.DateField(blank=True, help_text='Ngày bắt đầu công tác', null=True)),
                ('status', models.CharField(default='ACTIVE', help_text='ACTIVE (Đang công tác), RETIRED (Nghỉ hưu), RESIGNED (Nghỉ việc)', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_lecturers',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_code', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(blank=True, help_text='Giáo vụ, Kế toán, Chuyên viên...', max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Nhiệm vụ phụ trách', null=True)),
                ('join_date', models.DateField(blank=True, help_text='Ngày bắt đầu công tác', null=True)),
                ('status', models.CharField(default='ACTIVE', help_text='ACTIVE, RETIRED, RESIGNED', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_staffs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='ACTIVE', help_text='ACTIVE, PAUSED, GRADUATED, DROPPED_OUT', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True)),
                ('place_of_birth', models.CharField(blank=True, help_text='Nơi sinh / Quê quán', max_length=255, null=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Email cá nhân dự phòng', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ tạm trú hiện tại', null=True)),
                ('permanent_address', models.TextField(blank=True, help_text='Hộ khẩu thường trú', null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True)),
                ('health_insurance_number', models.CharField(blank=True, help_text='Mã BHYT', max_length=50, null=True)),
                ('parent_info', models.JSONField(blank=True, help_text='Thông tin phụ huynh: Tên, SĐT, Địa chỉ', null=True)),
                ('documents', models.JSONField(blank=True, help_text='Danh sách URLs giấy tờ đính kèm (CCCD, học bạ)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_students',
            },
        ),
    ]
