# Generated by Django 6.0.7 on 2026-07-18 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_alter_cohort_admission_year_alter_cohort_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lecturer_code', models.CharField(max_length=50, unique=True)),
                ('academic_title', models.CharField(blank=True, help_text='Thạc sĩ, Tiến sĩ, PGS, GS...', max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, help_text='Cơ hữu, Thỉnh giảng', max_length=50, null=True)),
                ('teaching_domain', models.TextField(blank=True, help_text='Chuyên môn/Lĩnh vực giảng dạy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='master_data.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturers',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_code', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(blank=True, help_text='Giáo vụ, Kế toán, Chuyên viên...', max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Nhiệm vụ phụ trách', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='master_data.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='ACTIVE', help_text='ACTIVE, PAUSED, GRADUATED, DROPPED_OUT', max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_info', models.JSONField(blank=True, help_text='Thông tin phụ huynh: Tên, SĐT, Địa chỉ', null=True)),
                ('documents', models.JSONField(blank=True, help_text='Danh sách URLs giấy tờ đính kèm (CCCD, học bạ)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrative_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.administrativeclass')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
