# Generated by Django 6.0.7 on 2026-07-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('master_data', '0004_alter_cohort_admission_year_alter_cohort_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='degree',
            field=models.CharField(blank=True, help_text='Cử nhân, Thạc sĩ, Tiến sĩ...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='ethnicity',
            field=models.CharField(blank=True, default='Kinh', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='join_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu công tác', null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='nationality',
            field=models.CharField(blank=True, default='Việt Nam', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='religion',
            field=models.CharField(blank=True, default='Không', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='status',
            field=models.CharField(default='ACTIVE', help_text='ACTIVE (Đang công tác), RETIRED (Nghỉ hưu), RESIGNED (Nghỉ việc)', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree',
            field=models.CharField(blank=True, help_text='Cử nhân, Thạc sĩ...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='join_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu công tác', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='ACTIVE', help_text='ACTIVE, RETIRED, RESIGNED', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Số TK Ngân hàng - Tên Ngân hàng', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education_system',
            field=models.ForeignKey(blank=True, help_text='Hệ đào tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.educationsystem'),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(blank=True, default='Kinh', help_text='Dân tộc', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='health_insurance_number',
            field=models.CharField(blank=True, help_text='Mã BHYT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Việt Nam', help_text='Quốc tịch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Hộ khẩu thường trú', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Email cá nhân dự phòng', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='Nơi sinh / Quê quán', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='priority_category',
            field=models.ForeignKey(blank=True, help_text='Đối tượng ưu tiên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.prioritycategory'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='Không', help_text='Tôn giáo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='academic_title',
            field=models.CharField(blank=True, help_text='Giảng viên, PGS, GS...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text='Địa chỉ tạm trú hiện tại', null=True),
        ),
    ]
