# Generated by Django 6.0.7 on 2026-07-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='academic_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='master_data.academictitle'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='master_data.degree'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='master_data.ethnicity'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='master_data.nationality'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='master_data.religion'),
        ),
    ]
