# Generated by Django 6.0.7 on 2026-07-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='master_data.degree'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='administrative_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.administrativeclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.ForeignKey(blank=True, help_text='Loại hình tuyển sinh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.admissiontype'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_system',
            field=models.ForeignKey(blank=True, help_text='Hệ đào tạo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.educationsystem'),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.ethnicity'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.nationality'),
        ),
        migrations.AddField(
            model_name='student',
            name='priority_category',
            field=models.ForeignKey(blank=True, help_text='Đối tượng ưu tiên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.prioritycategory'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.religion'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
