# Generated by Django 6.0.7 on 2026-07-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_initial'),
        ('master_data', '0002_coursetype_position_administrativeclass_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Chức vụ (Trưởng phòng, Giáo vụ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='master_data.position'),
        ),
    ]
