# Generated by Django 6.0.7 on 2026-08-07 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_staff_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(help_text='Loại chứng chỉ (VD: TOEIC, IELTS, MOS, GDQP)', max_length=100)),
                ('certificate_name', models.CharField(help_text='Tên cụ thể (VD: TOEIC 600, IELTS 6.5)', max_length=255)),
                ('issue_date', models.DateField(help_text='Ngày cấp')),
                ('expiration_date', models.DateField(blank=True, help_text='Ngày hết hạn (nếu có)', null=True)),
                ('score', models.CharField(blank=True, help_text='Điểm hoặc Xếp loại', max_length=50, null=True)),
                ('provider', models.CharField(blank=True, help_text='Tổ chức cấp', max_length=255, null=True)),
                ('file_proof', models.FileField(blank=True, help_text='Minh chứng (Ảnh/PDF)', null=True, upload_to='certificates/')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='hr.student')),
            ],
            options={
                'db_table': 'hr_student_certificates',
            },
        ),
    ]
