# Generated by Django 6.0.7 on 2026-08-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_studentcertificate'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='staff',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='master_data.ethnicity'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='master_data.nationality'),
        ),
        migrations.AddField(
            model_name='staff',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='master_data.religion'),
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Khóa tuyển sinh', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master_data.cohort'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Ngày nhập học', null=True),
        ),
    ]
