# Generated by Django 6.0.7 on 2026-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_lecturer_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcertificate',
            options={'ordering': ['-created_at']},
        ),
    ]
