# Generated by Django 6.0.7 on 2026-07-17 18:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.major')),
            ],
            options={
                'db_table': 'curriculum_courses',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('total_credits', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.major')),
            ],
            options={
                'db_table': 'curriculum_training_programs',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.course')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='curriculum.course')),
            ],
            options={
                'db_table': 'curriculum_prerequisites',
                'unique_together': {('course', 'required_course')},
            },
        ),
    ]
