# Generated by Django 6.0.7 on 2026-07-24 09:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã môn học (VD: IT101)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên môn học', max_length=255)),
                ('credits', models.IntegerField(help_text='Số tín chỉ (VD: 3)')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'curriculum_courses',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_capacity', models.IntegerField(default=10, help_text='Sĩ số tối thiểu')),
                ('max_capacity', models.IntegerField(default=50, help_text='Sĩ số tối đa')),
                ('current_enrollment', models.IntegerField(default=0, help_text='Số lượng sinh viên đã đăng ký')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('attendance_weight', models.DecimalField(decimal_places=2, default=0.1, help_text='Trọng số điểm chuyên cần (0.00 -> 1.00)', max_digits=3)),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=0.2, help_text='Trọng số điểm giữa kỳ', max_digits=3)),
                ('final_weight', models.DecimalField(decimal_places=2, default=0.7, help_text='Trọng số điểm cuối kỳ', max_digits=3)),
                ('status', models.CharField(choices=[('PLANNED', 'Theo kế hoạch'), ('OPEN', 'Mở đăng ký'), ('CLOSED', 'Đóng đăng ký'), ('CANCELLED', 'Đã hủy')], default='PLANNED', max_length=20)),
            ],
            options={
                'db_table': 'curriculum_course_offerings',
            },
        ),
        migrations.CreateModel(
            name='EquivalentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_equivalent_courses',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_prerequisites',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Thứ 2'), ('TUESDAY', 'Thứ 3'), ('WEDNESDAY', 'Thứ 4'), ('THURSDAY', 'Thứ 5'), ('FRIDAY', 'Thứ 6'), ('SATURDAY', 'Thứ 7'), ('SUNDAY', 'Chủ nhật')], help_text='Ngày học trong tuần', max_length=20)),
                ('start_period', models.IntegerField(help_text='Tiết bắt đầu (1-12)')),
                ('end_period', models.IntegerField(help_text='Tiết kết thúc (1-12)')),
                ('room', models.CharField(help_text='Mã phòng học (nhập tay hoặc map với danh mục phòng học)', max_length=50)),
            ],
            options={
                'db_table': 'curriculum_schedules',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tên kế hoạch (VD: Kế hoạch HK1 - 2024 Khoa CNTT)', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20)),
            ],
            options={
                'db_table': 'curriculum_training_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã chương trình (VD: CTTT-CNTT)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên chương trình đào tạo', max_length=255)),
                ('total_credits', models.IntegerField(help_text='Tổng số tín chỉ yêu cầu tốt nghiệp')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'curriculum_training_programs',
            },
        ),
    ]
