# Generated by Django 6.0.7 on 2026-07-17 19:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('master_data', '0002_academicyear_educationsystem_remove_semester_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Mã môn học (VD: IT101)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(help_text='Số tín chỉ (VD: 3)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(help_text='Thuộc ngành học nào', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Tên môn học', max_length=255),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(help_text='Môn học đang xét', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='required_course',
            field=models.ForeignKey(help_text='Môn học bắt buộc phải học trước', on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='curriculum.course'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='code',
            field=models.CharField(help_text='Mã chương trình (VD: CTTT-CNTT)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='major',
            field=models.ForeignKey(help_text='Chương trình thuộc ngành nào', on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.major'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='name',
            field=models.CharField(help_text='Tên chương trình đào tạo', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='total_credits',
            field=models.IntegerField(help_text='Tổng số tín chỉ yêu cầu tốt nghiệp'),
        ),
        migrations.CreateModel(
            name='EquivalentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Môn học trong khung chương trình cũ', on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_to', to='curriculum.course')),
                ('equivalent_course', models.ForeignKey(help_text='Môn học mới dùng để thay thế', on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_for', to='curriculum.course')),
            ],
            options={
                'db_table': 'curriculum_equivalent_courses',
                'unique_together': {('course', 'equivalent_course')},
            },
        ),
    ]
