# Generated by Django 6.0.7 on 2026-07-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('hr', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(help_text='Thuộc ngành học nào', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.major'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Giảng viên phụ trách', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='hr.lecturer'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='master_data.semester'),
        ),
        migrations.AddField(
            model_name='equivalentcourse',
            name='course',
            field=models.ForeignKey(help_text='Môn học trong khung chương trình cũ', on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_to', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='equivalentcourse',
            name='equivalent_course',
            field=models.ForeignKey(help_text='Môn học mới dùng để thay thế', on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_for', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(help_text='Môn học đang xét', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='required_course',
            field=models.ForeignKey(help_text='Môn học bắt buộc phải học trước', on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.courseoffering'),
        ),
    ]
