# Generated by Django 6.0.7 on 2026-07-22 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='department',
            field=models.ForeignKey(help_text='Khoa chủ quản lập kế hoạch', on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='master_data.semester'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='training_plan',
            field=models.ForeignKey(help_text='Thuộc Kế hoạch đào tạo nào', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='curriculum.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='major',
            field=models.ForeignKey(help_text='Chương trình thuộc ngành nào', on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.major'),
        ),
        migrations.AlterUniqueTogether(
            name='equivalentcourse',
            unique_together={('course', 'equivalent_course')},
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('course', 'required_course')},
        ),
    ]
