# Generated by Django 6.0.7 on 2026-07-21 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_course_code_alter_course_credits_and_more'),
        ('hr', '0001_initial'),
        ('master_data', '0004_alter_cohort_admission_year_alter_cohort_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_capacity', models.IntegerField(default=10, help_text='Sĩ số tối thiểu')),
                ('max_capacity', models.IntegerField(default=50, help_text='Sĩ số tối đa')),
                ('current_enrollment', models.IntegerField(default=0, help_text='Số lượng sinh viên đã đăng ký')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('attendance_weight', models.DecimalField(decimal_places=2, default=0.1, help_text='Trọng số điểm chuyên cần (0.00 -> 1.00)', max_digits=3)),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=0.2, help_text='Trọng số điểm giữa kỳ', max_digits=3)),
                ('final_weight', models.DecimalField(decimal_places=2, default=0.7, help_text='Trọng số điểm cuối kỳ', max_digits=3)),
                ('status', models.CharField(choices=[('PLANNED', 'Theo kế hoạch'), ('OPEN', 'Mở đăng ký'), ('CLOSED', 'Đóng đăng ký'), ('CANCELLED', 'Đã hủy')], default='PLANNED', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='curriculum.course')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Giảng viên phụ trách', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='hr.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='master_data.semester')),
            ],
            options={
                'db_table': 'curriculum_course_offerings',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Thứ 2'), ('TUESDAY', 'Thứ 3'), ('WEDNESDAY', 'Thứ 4'), ('THURSDAY', 'Thứ 5'), ('FRIDAY', 'Thứ 6'), ('SATURDAY', 'Thứ 7'), ('SUNDAY', 'Chủ nhật')], help_text='Ngày học trong tuần', max_length=20)),
                ('start_period', models.IntegerField(help_text='Tiết bắt đầu (1-12)')),
                ('end_period', models.IntegerField(help_text='Tiết kết thúc (1-12)')),
                ('room', models.CharField(help_text='Mã phòng học (nhập tay hoặc map với danh mục phòng học)', max_length=50)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.courseoffering')),
            ],
            options={
                'db_table': 'curriculum_schedules',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tên kế hoạch (VD: Kế hoạch HK1 - 2024 Khoa CNTT)', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Khoa chủ quản lập kế hoạch', on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='master_data.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='master_data.semester')),
            ],
            options={
                'db_table': 'curriculum_training_plans',
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='training_plan',
            field=models.ForeignKey(help_text='Thuộc Kế hoạch đào tạo nào', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='curriculum.trainingplan'),
        ),
    ]
