# Generated by Django 6.0.7 on 2026-07-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_initial'),
        ('master_data', '0002_coursetype_position_administrativeclass_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(help_text='Loại học phần', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.coursetype'),
        ),
    ]
