# Generated by Django 6.0.7 on 2026-07-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_course_course_type'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(help_text='Phòng học', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='master_data.room'),
        ),
    ]
