# Generated by Django 6.0.7 on 2026-08-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_schedule_room'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default='32cb1fde-8c7f-4a3a-bb01-37c349cffff7', help_text='Thuộc Bộ môn/Khoa quản lý', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_credits',
            field=models.IntegerField(default=0, help_text='Số tín chỉ thực hành'),
        ),
        migrations.AddField(
            model_name='course',
            name='theory_credits',
            field=models.IntegerField(default=0, help_text='Số tín chỉ lý thuyết'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='cohort',
            field=models.ForeignKey(default='129e50ae-09ba-46ca-9a82-287e26e78978', help_text='Áp dụng cho khóa nào', on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.cohort'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(help_text='Tổng số tín chỉ (VD: 3)'),
        ),
    ]
