# Generated by Django 6.0.7 on 2026-08-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_course_major_course_department_and_more'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Chuyên ngành áp dụng (nếu có)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.specialization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Thuộc Bộ môn/Khoa quản lý', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.department'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='cohort',
            field=models.ForeignKey(help_text='Áp dụng cho khóa nào', on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='master_data.cohort'),
        ),
    ]
