# Generated by Django 6.0.7 on 2026-08-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_trainingprogram_specialization_and_more'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, help_text='Loại học phần', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master_data.coursetype'),
        ),
    ]
