# Generated by Django 6.0.7 on 2026-08-25 15:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_course_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã khối (VD: K1-DAICUONG)', max_length=50)),
                ('name', models.CharField(help_text='Tên khối (VD: Khối kiến thức chuyên ngành)', max_length=255)),
                ('mandatory_credits', models.PositiveSmallIntegerField(default=0, help_text='Số TC bắt buộc phải đạt')),
                ('elective_credits', models.PositiveSmallIntegerField(default=0, help_text='Số TC tự chọn tối thiểu phải đạt')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_blocks', to='curriculum.trainingprogram')),
            ],
            options={
                'db_table': 'curriculum_knowledge_blocks',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_expected', models.PositiveSmallIntegerField(help_text='Học kỳ dự kiến (VD: 1-12)')),
                ('is_mandatory', models.BooleanField(default=True, help_text='True: Bắt buộc | False: Tự chọn')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_program_courses', to='curriculum.course')),
                ('knowledge_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum.knowledgeblock')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='curriculum.trainingprogram')),
            ],
            options={
                'db_table': 'curriculum_training_program_courses',
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgeblock',
            constraint=models.UniqueConstraint(fields=('training_program', 'code'), name='unique_training_program_block_code'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingprogramcourse',
            unique_together={('training_program', 'course')},
        ),
    ]
