# Generated by Django 6.0 on 2026-01-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parent')),
            ],
        ),
    ]
