# Generated by Django 6.0.7 on 2026-07-22 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã năm học (VD: 2024-2025)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên năm học (VD: Năm học 2024-2025)', max_length=255)),
                ('is_current', models.BooleanField(default=False, help_text='Có phải là năm học hiện tại không?')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_academic_years',
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã khóa học (VD: K2024)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên khóa học (VD: Khóa 2024-2028)', max_length=255)),
                ('admission_year', models.IntegerField(help_text='Năm tuyển sinh (VD: 2024)')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_cohorts',
            },
        ),
        migrations.CreateModel(
            name='EducationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã hệ đào tạo (VD: CQ)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hệ đào tạo (VD: Chính quy)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_education_systems',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã hình thức (VD: TU_LUAN)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hình thức thi', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_exam_types',
            },
        ),
        migrations.CreateModel(
            name='PriorityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã ưu tiên (VD: DT1)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên đối tượng ưu tiên', max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Phần trăm giảm học phí (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_priority_categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã phòng (VD: A1-201)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên/Mô tả phòng', max_length=255, null=True)),
                ('type', models.CharField(choices=[('THEORY', 'Lý thuyết'), ('PRACTICE', 'Thực hành'), ('HALL', 'Hội trường')], help_text='Loại phòng (Lý thuyết, Thực hành)', max_length=50)),
                ('capacity', models.IntegerField(help_text='Sức chứa tối đa (số sinh viên)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang dùng'), ('MAINTENANCE', 'Bảo trì')], default='ACTIVE', help_text='Tình trạng phòng', max_length=50)),
            ],
            options={
                'db_table': 'master_data_rooms',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã đơn vị (VD: CNTT, GDTC)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên đơn vị', max_length=255)),
                ('type', models.CharField(choices=[('FACULTY', 'Khoa'), ('DEPARTMENT', 'Bộ môn'), ('CENTER', 'Trung tâm'), ('OFFICE', 'Phòng ban')], help_text='Loại đơn vị (Khoa/Bộ môn...)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
                ('manager', models.ForeignKey(blank=True, help_text='Trưởng đơn vị (Tham chiếu đến Giảng viên)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.lecturer')),
                ('parent', models.ForeignKey(blank=True, help_text='Đơn vị cha (VD: Bộ môn thuộc Khoa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.department')),
            ],
            options={
                'db_table': 'master_data_departments',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã ngành học (VD: 7480201)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên ngành học', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
                ('department', models.ForeignKey(help_text='Thuộc khoa/đơn vị nào', on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='master_data.department')),
            ],
            options={
                'db_table': 'master_data_majors',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('advisor', models.ForeignKey(blank=True, help_text='Giảng viên cố vấn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to='hr.lecturer')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_classes', to='master_data.cohort')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_classes', to='master_data.major')),
            ],
            options={
                'verbose_name_plural': 'Administrative Classes',
                'db_table': 'master_data_administrative_classes',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã học kỳ (VD: 2024-HK1)', max_length=50, unique=True)),
                ('season', models.CharField(choices=[('HK1', 'Học kỳ 1'), ('HK2', 'Học kỳ 2'), ('HE', 'Học kỳ Hè')], help_text='Mùa học kỳ (HK1, HK2, Hè)', max_length=50)),
                ('start_date', models.DateField(help_text='Ngày bắt đầu học kỳ')),
                ('end_date', models.DateField(help_text='Ngày kết thúc học kỳ')),
                ('is_current', models.BooleanField(default=False, help_text='Có phải là học kỳ hiện tại không?')),
                ('academic_year', models.ForeignKey(help_text='Thuộc năm học nào', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='master_data.academicyear')),
            ],
            options={
                'db_table': 'master_data_semesters',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã chuyên ngành', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên chuyên ngành', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
                ('major', models.ForeignKey(help_text='Thuộc ngành học nào', on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='master_data.major')),
            ],
            options={
                'db_table': 'master_data_specializations',
            },
        ),
    ]
