# Generated by Django 6.0.7 on 2026-07-17 19:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã năm học (VD: 2024-2025)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên năm học (VD: Năm học 2024-2025)', max_length=255)),
                ('is_current', models.BooleanField(default=False, help_text='Có phải là năm học hiện tại không?')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_academic_years',
            },
        ),
        migrations.CreateModel(
            name='EducationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã hệ đào tạo (VD: CQ)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hệ đào tạo (VD: Chính quy)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'master_data_education_systems',
            },
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='admission_year',
            field=models.IntegerField(help_text='Năm tuyển sinh (VD: 2024)'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='code',
            field=models.CharField(help_text='Mã khóa học (VD: K2024)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(help_text='Tên khóa học (VD: Khóa 2024-2028)', max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Mã đơn vị (VD: CNTT, GDTC)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.UUIDField(blank=True, help_text='ID của Trưởng đơn vị (Tham chiếu lỏng đến bảng Nhân sự)', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Tên đơn vị', max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Đơn vị cha (VD: Bộ môn thuộc Khoa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('FACULTY', 'Khoa'), ('DEPARTMENT', 'Bộ môn'), ('CENTER', 'Trung tâm'), ('OFFICE', 'Phòng ban')], help_text='Loại đơn vị (Khoa/Bộ môn...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='code',
            field=models.CharField(help_text='Mã hình thức (VD: TU_LUAN)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(help_text='Tên hình thức thi', max_length=255),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(help_text='Mã ngành học (VD: 7480201)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.ForeignKey(help_text='Thuộc khoa/đơn vị nào', on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='master_data.department'),
        ),
        migrations.AlterField(
            model_name='major',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(help_text='Tên ngành học', max_length=255),
        ),
        migrations.AlterField(
            model_name='prioritycategory',
            name='code',
            field=models.CharField(help_text='Mã ưu tiên (VD: DT1)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='prioritycategory',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Phần trăm giảm học phí (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='prioritycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='prioritycategory',
            name='name',
            field=models.CharField(help_text='Tên đối tượng ưu tiên', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Sức chứa tối đa (số sinh viên)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(help_text='Mã phòng (VD: A1-201)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, help_text='Tên/Mô tả phòng', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang dùng'), ('MAINTENANCE', 'Bảo trì')], default='ACTIVE', help_text='Tình trạng phòng', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('THEORY', 'Lý thuyết'), ('PRACTICE', 'Thực hành'), ('HALL', 'Hội trường')], help_text='Loại phòng (Lý thuyết, Thực hành)', max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(help_text='Mã học kỳ (VD: 2024-HK1)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(help_text='Ngày kết thúc học kỳ'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Có phải là học kỳ hiện tại không?'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('HK1', 'Học kỳ 1'), ('HK2', 'Học kỳ 2'), ('HE', 'Học kỳ Hè')], help_text='Mùa học kỳ (HK1, HK2, Hè)', max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(help_text='Ngày bắt đầu học kỳ'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(help_text='Thuộc năm học nào', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='master_data.academicyear'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã chuyên ngành', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên chuyên ngành', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
                ('major', models.ForeignKey(help_text='Thuộc ngành học nào', on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='master_data.major')),
            ],
            options={
                'db_table': 'master_data_specializations',
            },
        ),
    ]
