# Generated by Django 6.0.7 on 2026-07-29 15:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã loại học phần', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên loại học phần', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_course_types',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã chức vụ', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên chức vụ', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_positions',
            },
        ),
        migrations.AddField(
            model_name='administrativeclass',
            name='capacity',
            field=models.IntegerField(default=50, help_text='Sĩ số'),
        ),
        migrations.AddField(
            model_name='administrativeclass',
            name='education_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_classes', to='master_data.educationsystem'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_count',
            field=models.IntegerField(default=1, help_text='Số tầng'),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, help_text='Số điện thoại', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='website',
            field=models.URLField(blank=True, help_text='Website', null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='level',
            field=models.CharField(choices=[('UNDERGRAD', 'Đại học'), ('POSTGRAD', 'Thạc sĩ'), ('PHD', 'Tiến sĩ')], default='UNDERGRAD', help_text='Trình độ đào tạo', max_length=50),
        ),
        migrations.AddField(
            model_name='major',
            name='standard_duration_years',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Thời gian đào tạo chuẩn (năm)', max_digits=4),
        ),
        migrations.AddField(
            model_name='prioritycategory',
            name='bonus_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Điểm cộng ưu tiên', max_digits=4),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.JSONField(blank=True, default=dict, help_text='Cơ sở vật chất: máy chiếu, máy lạnh...'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, help_text='Tầng'),
        ),
        migrations.AddField(
            model_name='semester',
            name='grade_submission_deadline',
            field=models.DateField(blank=True, help_text='Hạn chót nộp điểm', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='Ngày kết thúc đăng ký tín chỉ', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='registration_start_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu đăng ký tín chỉ', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='tuition_deadline',
            field=models.DateField(blank=True, help_text='Hạn chót đóng học phí', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Trưởng đơn vị (Tham chiếu đến User)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(help_text='Thuộc tòa nhà nào', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='master_data.building'),
        ),
    ]
