# Generated by Django 6.0.7 on 2026-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_coursetype_position_administrativeclass_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, help_text='Ngày kết thúc', null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu', null=True),
        ),
    ]
