# Generated by Django 6.0.7 on 2026-07-18 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_academicyear_educationsystem_remove_semester_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='admission_year',
            field=models.IntegerField(help_text='Năm tuyển sinh (VD: 2020)'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='code',
            field=models.CharField(help_text='Mã khóa học (VD: K62)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(help_text='Tên khóa học (VD: Khóa 62)', max_length=255),
        ),
        migrations.CreateModel(
            name='AdministrativeClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('advisor_id', models.UUIDField(blank=True, help_text='ID của Giảng viên cố vấn (sẽ map với hr.Lecturer)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_classes', to='master_data.cohort')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_classes', to='master_data.major')),
            ],
            options={
                'verbose_name_plural': 'Administrative Classes',
                'db_table': 'master_data_administrative_classes',
            },
        ),
    ]
