# Generated by Django 6.0.7 on 2026-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_cohort_admission_year_alter_cohort_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='admission_year',
            field=models.IntegerField(help_text='Năm tuyển sinh (VD: 2024)'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='code',
            field=models.CharField(help_text='Mã khóa học (VD: K2024)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(help_text='Tên khóa học (VD: Khóa 2024-2028)', max_length=255),
        ),
    ]
