# Generated by Django 6.0 on 2026-03-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khoa')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khoa')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Khoa / Bộ môn',
                'verbose_name_plural': 'Khoa / Bộ môn',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgv', models.CharField(max_length=20, unique=True, verbose_name='Mã giáo viên')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính')),
                ('degree', models.CharField(choices=[('bachelor', 'Cử nhân'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ')], default='bachelor', max_length=50, verbose_name='Bằng cấp')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chuyên môn')),
                ('status', models.BooleanField(default=True, verbose_name='Đang dạy')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.department', verbose_name='Khoa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ giáo viên',
                'verbose_name_plural': 'Hồ sơ giáo viên',
            },
        ),
    ]
