# Generated by Django 6.0.6 on 2026-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Hồ sơ giảng viên', 'verbose_name_plural': 'Hồ sơ giảng viên'},
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='mgv',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã số giảng viên'),
        ),
    ]
