# Generated by Django 6.0.7 on 2026-08-07 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_studentcertificate'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseCouncil',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên hội đồng', max_length=255)),
                ('defense_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.major')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council_presidents', to='hr.lecturer')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.room')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council_secretaries', to='hr.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.semester')),
            ],
            options={
                'db_table': 'graduation_defense_councils',
            },
        ),
        migrations.CreateModel(
            name='GraduationCandidate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_credits', models.IntegerField(default=0)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('missing_conditions', models.JSONField(default=list, help_text='Các điều kiện còn thiếu')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('PASSED', 'Đủ điều kiện'), ('FAILED', 'Không đủ điều kiện'), ('APPROVED', 'Đã phê duyệt tốt nghiệp')], default='PENDING', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='hr.student')),
            ],
            options={
                'db_table': 'graduation_candidates',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diploma_number', models.CharField(help_text='Số hiệu văn bằng', max_length=100, unique=True)),
                ('registry_number', models.CharField(help_text='Số vào sổ cấp bằng', max_length=100, unique=True)),
                ('issue_date', models.DateField(help_text='Ngày ký cấp bằng')),
                ('classification', models.CharField(help_text='Xếp loại tốt nghiệp (Xuất sắc, Giỏi, Khá, TB Khá, TB)', max_length=50)),
                ('status', models.CharField(choices=[('PRINTED', 'Đã in bằng'), ('ISSUED', 'Đã phát cho SV'), ('REVOKED', 'Bị thu hồi')], default='PRINTED', max_length=20)),
                ('received_by', models.CharField(blank=True, help_text='Người nhận (Sinh viên hoặc người được ủy quyền)', max_length=255, null=True)),
                ('receive_date', models.DateField(blank=True, help_text='Ngày nhận bằng thực tế', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='hr.student')),
                ('candidate_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graduation.graduationcandidate')),
            ],
            options={
                'db_table': 'graduation_diplomas',
            },
        ),
        migrations.CreateModel(
            name='GraduationCondition',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.CharField(blank=True, help_text='Khóa học (VD: K64). Nếu trống thì áp dụng chung.', max_length=50, null=True)),
                ('total_credits_required', models.IntegerField(help_text='Tổng số tín chỉ yêu cầu')),
                ('min_gpa', models.DecimalField(decimal_places=2, help_text='GPA tối thiểu', max_digits=4)),
                ('required_certificates', models.JSONField(default=list, help_text="Danh sách loại chứng chỉ bắt buộc (VD: ['TOEIC', 'GDQP'])")),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_conditions', to='master_data.major')),
            ],
            options={
                'db_table': 'graduation_conditions',
            },
        ),
        migrations.CreateModel(
            name='GraduationSession',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên đợt xét (VD: Đợt 1 năm 2024)', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PROCESSING', 'Đang xử lý'), ('FINISHED', 'Đã hoàn tất')], default='DRAFT', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.semester')),
            ],
            options={
                'db_table': 'graduation_sessions',
            },
        ),
        migrations.AddField(
            model_name='graduationcandidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='graduation.graduationsession'),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Tên đề tài', max_length=255)),
                ('advisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reviewer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('council_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('DEFENDING', 'Chờ bảo vệ'), ('PASSED', 'Bảo vệ thành công'), ('FAILED', 'Bảo vệ thất bại')], default='REGISTERED', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advised_theses', to='hr.lecturer')),
                ('council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='graduation.defensecouncil')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theses', to='hr.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.semester')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='hr.student')),
            ],
            options={
                'db_table': 'graduation_theses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='graduationcandidate',
            unique_together={('session', 'student')},
        ),
    ]
