# Generated by Django 6.0.7 on 2026-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systembackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key']},
        ),
    ]
