# Generated by Django 6.0 on 2026-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng'), ('late', 'Đi muộn'), ('excused', 'Có phép')], default='present', max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tên lớp')),
                ('max_students', models.PositiveSmallIntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('status', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sinh viên trong lớp',
                'verbose_name_plural': 'Sinh viên trong lớp',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn')),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Số tín chỉ')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Phân công dạy',
                'verbose_name_plural': 'Phân công dạy',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(verbose_name='Điểm')),
                ('max_marks', models.FloatField(default=10.0, verbose_name='Điểm tối đa')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kết quả thi',
                'verbose_name_plural': 'Kết quả thi',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên loại')),
                ('weight', models.FloatField(default=1.0, verbose_name='Hệ số')),
            ],
            options={
                'verbose_name': 'Loại thi',
                'verbose_name_plural': 'Loại thi',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên khối')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Khối lớp',
                'verbose_name_plural': 'Khối lớp',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên học kỳ')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Năm học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Học kỳ hiện tại')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
                'ordering': ['-start_date'],
            },
        ),
    ]
