# Generated by Django 6.0 on 2026-03-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacherprofile', verbose_name='Giáo viên chủ nhiệm'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='classroomstudent',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='classroomstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.course'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.examtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.grade', verbose_name='Khối'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade', verbose_name='Khối'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.semester', verbose_name='Học kỳ'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'student', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together={('classroom', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('classroom', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'course', 'semester', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'semester')},
        ),
    ]
