# Generated by Django 6.0.6 on 2026-06-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('teachers', '0002_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Khóa / Năm học', 'verbose_name_plural': 'Khóa / Năm học'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade', verbose_name='Khóa/Năm'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacherprofile', verbose_name='Giảng viên chủ nhiệm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên khóa/năm'),
        ),
    ]
