# Generated by Django 6.0.7 on 2026-07-22 22:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDisciplineCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Mã danh mục (VD: KT-01)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên danh mục (VD: Khiển trách)', max_length=255)),
                ('type', models.CharField(choices=[('REWARD', 'Khen thưởng'), ('DISCIPLINE', 'Kỷ luật')], help_text='Phân loại: Khen thưởng hay Kỷ luật', max_length=50)),
                ('level', models.CharField(blank=True, choices=[('KHIEN_TRACH', 'Khiển trách'), ('CANH_CAO', 'Cảnh cáo'), ('DINH_CHI', 'Đình chỉ học tập'), ('BUOC_THOI_HOC', 'Buộc thôi học'), ('GIAY_KHEN', 'Giấy khen'), ('BANG_KHEN', 'Bằng khen'), ('HOC_BONG', 'Học bổng')], help_text='Mức độ', max_length=50, null=True)),
                ('training_points_impact', models.IntegerField(default=0, help_text='Điểm rèn luyện cộng thêm (nếu khen thưởng) hoặc trừ đi (nếu kỷ luật)')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động')),
            ],
            options={
                'db_table': 'affairs_reward_discipline_categories',
            },
        ),
    ]
