# Generated by Django 6.0.7 on 2026-08-07 12:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0001_initial'),
        ('hr', '0004_alter_staff_position'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('topic', models.CharField(help_text='Chủ đề tư vấn (VD: Cảnh báo học vụ, Kế hoạch học tập)', max_length=255)),
                ('notes', models.TextField(help_text='Nội dung chi tiết buổi tư vấn')),
                ('advisor', models.ForeignKey(help_text='CVHT (Cán bộ/Giảng viên)', on_delete=django.db.models.deletion.CASCADE, related_name='advising_sessions', to='hr.staff')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_sessions', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_sessions', to='hr.student')),
            ],
            options={
                'db_table': 'affairs_advising_sessions',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tên học bổng', max_length=255)),
                ('type', models.CharField(choices=[('ACADEMIC', 'Khuyến khích học tập'), ('SPONSOR', 'Tài trợ doanh nghiệp'), ('GOVERNMENT', 'Hỗ trợ chính phủ')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền học bổng', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REVOKED', 'Đã thu hồi')], default='PENDING', max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='hr.student')),
            ],
            options={
                'db_table': 'affairs_scholarships',
            },
        ),
        migrations.CreateModel(
            name='StudentRewardDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_number', models.CharField(blank=True, help_text='Số quyết định', max_length=50, null=True)),
                ('decision_date', models.DateField(blank=True, help_text='Ngày quyết định', null=True)),
                ('reason', models.TextField(help_text='Lý do chi tiết')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REVOKED', 'Đã thu hồi')], default='DRAFT', max_length=20)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reward_disciplines', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='affairs.rewarddisciplinecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reward_disciplines', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_disciplines', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_disciplines', to='hr.student')),
            ],
            options={
                'db_table': 'affairs_student_reward_disciplines',
            },
        ),
        migrations.CreateModel(
            name='TrainingScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_assessment', models.IntegerField(default=0, help_text='Điểm SV tự đánh giá')),
                ('class_assessment', models.IntegerField(default=0, help_text='Điểm lớp đánh giá')),
                ('faculty_assessment', models.IntegerField(default=0, help_text='Điểm khoa/trường đánh giá (Final)')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REVOKED', 'Đã thu hồi')], default='DRAFT', max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_scores', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_scores', to='hr.student')),
            ],
            options={
                'db_table': 'affairs_training_scores',
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
