# Generated by Django 6.0.7 on 2026-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarddisciplinecategory',
            name='code',
            field=models.CharField(help_text='Mã danh mục (VD: KT-01)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rewarddisciplinecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='rewarddisciplinecategory',
            name='level',
            field=models.CharField(blank=True, choices=[('KHIEN_TRACH', 'Khiển trách'), ('CANH_CAO', 'Cảnh cáo'), ('DINH_CHI', 'Đình chỉ học tập'), ('BUOC_THOI_HOC', 'Buộc thôi học'), ('GIAY_KHEN', 'Giấy khen'), ('BANG_KHEN', 'Bằng khen'), ('HOC_BONG', 'Học bổng')], help_text='Mức độ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rewarddisciplinecategory',
            name='name',
            field=models.CharField(help_text='Tên danh mục (VD: Khiển trách)', max_length=255),
        ),
        migrations.AlterField(
            model_name='rewarddisciplinecategory',
            name='type',
            field=models.CharField(choices=[('REWARD', 'Khen thưởng'), ('DISCIPLINE', 'Kỷ luật')], help_text='Phân loại: Khen thưởng hay Kỷ luật', max_length=50),
        ),
    ]
