# Generated by Django 6.0.7 on 2026-08-07 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_alter_staff_position'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_credits', models.IntegerField(default=0)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, help_text='Học phí gốc', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền được giảm', max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền phải đóng (gốc - giảm)', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đã đóng', max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='hr.student')),
            ],
            options={
                'db_table': 'student_debts',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Gateway')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('reference_code', models.CharField(blank=True, help_text='Mã giao dịch / Mã cổng thanh toán', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Cán bộ thu tiền (nếu đóng tiền mặt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to='hr.staff')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='hr.student')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.studentdebt')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.CreateModel(
            name='TuitionExemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Tỷ lệ giảm giá (%)', max_digits=5)),
                ('document_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_exemptions', to='master_data.prioritycategory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_exemptions', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_exemptions', to='hr.student')),
            ],
            options={
                'db_table': 'tuition_exemptions',
            },
        ),
        migrations.CreateModel(
            name='TuitionExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_due_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to='hr.staff')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_extensions', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_extensions', to='hr.student')),
            ],
            options={
                'db_table': 'tuition_extensions',
            },
        ),
        migrations.CreateModel(
            name='TuitionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_price', models.DecimalField(decimal_places=2, help_text='Đơn giá 1 tín chỉ', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_rules', to='master_data.academicyear')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_rules', to='master_data.major')),
            ],
            options={
                'db_table': 'tuition_rules',
                'unique_together': {('academic_year', 'major')},
            },
        ),
    ]
