# Generated by Django 6.0.7 on 2026-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
