# Generated by Django 6.0.7 on 2026-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_receipt_is_deleted_studentdebt_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='studentdebt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tuitionexemption',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tuitionextension',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tuitionrule',
            options={'ordering': ['-created_at']},
        ),
    ]
