# Generated by Django 5.2.15 on 2026-06-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_credit', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá/tín chỉ')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='Ngày áp dụng')),
            ],
            options={
                'verbose_name': 'Cấu hình học phí',
                'verbose_name_plural': 'Cấu hình học phí',
            },
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='Học kỳ')),
                ('total_credits', models.IntegerField(verbose_name='Tổng tín chỉ')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa nộp'), ('PAID', 'Đã nộp'), ('OVERDUE', 'Nợ')], default='UNPAID', max_length=10, verbose_name='Trạng thái')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn nộp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='students.studentprofile', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Học phí',
                'verbose_name_plural': 'Học phí',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TuitionFeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('course_code', models.CharField(max_length=20, verbose_name='Mã môn')),
                ('credits', models.IntegerField(verbose_name='Tín chỉ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Thành tiền')),
                ('tuition_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.tuitionfee', verbose_name='Học phí')),
            ],
            options={
                'verbose_name': 'Chi tiết học phí',
                'verbose_name_plural': 'Chi tiết học phí',
            },
        ),
    ]
