# Generated by Django 5.2.15 on 2026-06-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('course_code', models.CharField(max_length=20, verbose_name='Mã môn')),
                ('credits', models.IntegerField(verbose_name='Tín chỉ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Thành tiền')),
                ('tuition_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.tuitionfee', verbose_name='Học phí')),
            ],
            options={
                'verbose_name': 'Chi tiết học phí',
                'verbose_name_plural': 'Chi tiết học phí',
            },
        ),
    ]
