# Generated by Django 6.0.7 on 2026-08-07 12:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0005_alter_schedule_room'),
        ('enrollment', '0002_initial'),
        ('hr', '0004_alter_staff_position'),
        ('master_data', '0003_academicyear_end_date_academicyear_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên kỳ thi', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='master_data.semester')),
            ],
            options={
                'db_table': 'exams_exam_sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(help_text='Số lượng sinh viên tối đa trong phòng thi')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rooms', to='curriculum.courseoffering')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_rooms', to='master_data.room')),
                ('supervisor', models.ForeignKey(help_text='Giám thị', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_exams', to='hr.staff')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rooms', to='exams.examsession')),
            ],
            options={
                'db_table': 'exams_exam_rooms',
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Lý do thay đổi điểm', null=True)),
                ('old_attendance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_attendance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('old_midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('old_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_grades', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_histories', to='enrollment.enrollment')),
            ],
            options={
                'db_table': 'exams_grade_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeReview',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Lý do xin phúc khảo')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã chấp nhận'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20)),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reviews', to='enrollment.enrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reviews', to='hr.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reviews', to='hr.student')),
            ],
            options={
                'db_table': 'exams_grade_reviews',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('semester_gpa_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('semester_credits', models.IntegerField(default=0, help_text='Số tín chỉ đạt trong kỳ')),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('cumulative_gpa_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('cumulative_credits', models.IntegerField(default=0, help_text='Tổng tín chỉ tích lũy')),
                ('academic_standing', models.CharField(blank=True, choices=[('EXCELLENT', 'Xuất sắc'), ('GOOD', 'Giỏi'), ('FAIR', 'Khá'), ('AVERAGE', 'Trung bình'), ('WEAK', 'Yếu'), ('POOR', 'Kém')], max_length=20, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='hr.student')),
            ],
            options={
                'db_table': 'exams_student_academic_records',
                'ordering': ['student', 'semester__start_date'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
