# Generated by Django 6.0.7 on 2026-08-07 12:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsession_exam_type'),
        ('hr', '0004_alter_staff_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamRoom',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rooms', to='hr.student')),
            ],
            options={
                'db_table': 'exams_student_exam_rooms',
                'unique_together': {('exam_room', 'student')},
            },
        ),
    ]
