# Generated by Django 6.0.7 on 2026-08-07 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên mẫu báo cáo', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(help_text='STUDENT, FINANCE, ACADEMIC, HR, EXAMS', max_length=50)),
                ('columns', models.JSONField(default=list, help_text='Danh sách các cột cần xuất')),
                ('filters', models.JSONField(default=dict, help_text='Bộ lọc lưu sẵn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Report Template',
                'db_table': 'reports_custom_templates',
            },
        ),
        migrations.CreateModel(
            name='DataExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(help_text='Ví dụ: DANH_SACH_SINH_VIEN', max_length=100)),
                ('format', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], default='EXCEL', max_length=10)),
                ('filters_applied', models.JSONField(default=dict)),
                ('file_url', models.CharField(blank=True, help_text='Đường dẫn file đã xuất', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export History',
                'db_table': 'reports_export_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
