# Generated by Django 6.0.7 on 2026-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customreporttemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom Report Template'},
        ),
    ]
