# Generated by Django 6.0.7 on 2026-08-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otptoken',
            options={'ordering': ['-created_at']},
        ),
    ]
