# Generated by Django 6.0.7 on 2026-07-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
