# Generated by Django 6.0.7 on 2026-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_systemconfig_id_alter_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'code', 'type', 'is_used'], name='identity_ot_user_id_c77533_idx'),
        ),
    ]
