# Generated by Django 6.0.7 on 2026-07-21 01:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_courseoffering_schedule_trainingplan_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_type', models.CharField(choices=[('NORMAL', 'Học lần đầu'), ('RETAKE', 'Học lại'), ('IMPROVEMENT', 'Học cải thiện'), ('ADVANCED', 'Học vượt')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Từ chối')], default='APPROVED', max_length=20)),
                ('attendance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Khóa bản ghi, không cho sửa điểm')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='hr.student')),
            ],
            options={
                'db_table': 'enrollments',
                'unique_together': {('student', 'course_offering')},
            },
        ),
    ]
